namespace DiscreteDeviceAssigner
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variables
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up all resources that are in use
        /// </summary>
        /// <param name="disposing">True if managed resources should be released; Otherwise, false</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows The code generated by the form designer

        /// <summary>
        /// The designer supports the required methods - do not modify
        /// Use the code editor to modify the contents of this method
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.listView1 = new System.Windows.Forms.ListView();
            this.columnHeaderDevice = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeaderClass = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.columnHeaderLocation = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.contextMenuStrip = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.vMNameToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.OtherToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.lowMemoryMappedIoSpaceToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.LMMIOtoolStripTextBox = new System.Windows.Forms.ToolStripTextBox();
            this.toolStripSeparator4 = new System.Windows.Forms.ToolStripSeparator();
            this.highMemoryMappedIoSpaceToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.HMMIOtoolStripTextBox = new System.Windows.Forms.ToolStripTextBox();
            this.toolStripSeparator5 = new System.Windows.Forms.ToolStripSeparator();
            this.GCCTtoolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator2 = new System.Windows.Forms.ToolStripSeparator();
            this.AddDeviceToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.RemoveDeviceToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.CopyAddressToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.RefreshToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.contextMenuStrip.SuspendLayout();
            this.SuspendLayout();
            // 
            // listView1
            // 
            this.listView1.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.columnHeaderDevice,
            this.columnHeaderClass,
            this.columnHeaderLocation});
            this.listView1.FullRowSelect = true;
            this.listView1.HideSelection = false;
            this.listView1.Location = new System.Drawing.Point(12, 13);
            this.listView1.MultiSelect = false;
            this.listView1.Name = "listView1";
            this.listView1.Size = new System.Drawing.Size(815, 549);
            this.listView1.TabIndex = 0;
            this.listView1.UseCompatibleStateImageBehavior = false;
            this.listView1.View = System.Windows.Forms.View.Details;
            this.listView1.SelectedIndexChanged += new System.EventHandler(this.listView1_SelectedIndexChanged);
            this.listView1.MouseClick += new System.Windows.Forms.MouseEventHandler(this.listView1_MouseClick);
            // 
            // columnHeaderDevice
            // 
            this.columnHeaderDevice.Text = "Equipment";
            this.columnHeaderDevice.Width = 241;
            // 
            // columnHeaderClass
            // 
            this.columnHeaderClass.Text = "Type";
            this.columnHeaderClass.Width = 171;
            // 
            // columnHeaderLocation
            // 
            this.columnHeaderLocation.Text = "Address";
            this.columnHeaderLocation.Width = 398;
            // 
            // contextMenuStrip
            // 
            this.contextMenuStrip.ImageScalingSize = new System.Drawing.Size(20, 20);
            this.contextMenuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.vMNameToolStripMenuItem,
            this.OtherToolStripMenuItem,
            this.toolStripSeparator2,
            this.AddDeviceToolStripMenuItem,
            this.RemoveDeviceToolStripMenuItem,
            this.CopyAddressToolStripMenuItem,
            this.toolStripSeparator1,
            this.RefreshToolStripMenuItem});
            this.contextMenuStrip.Name = "contextMenuStrip";
            this.contextMenuStrip.Size = new System.Drawing.Size(205, 160);
            this.contextMenuStrip.Opening += new System.ComponentModel.CancelEventHandler(this.contextMenuStrip_Opening);
            // 
            // vMNameToolStripMenuItem
            // 
            this.vMNameToolStripMenuItem.Enabled = false;
            this.vMNameToolStripMenuItem.Name = "vMNameToolStripMenuItem";
            this.vMNameToolStripMenuItem.Size = new System.Drawing.Size(204, 24);
            this.vMNameToolStripMenuItem.Text = "VMName";
            // 
            // OtherToolStripMenuItem
            // 
            this.OtherToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.lowMemoryMappedIoSpaceToolStripMenuItem,
            this.LMMIOtoolStripTextBox,
            this.toolStripSeparator4,
            this.highMemoryMappedIoSpaceToolStripMenuItem,
            this.HMMIOtoolStripTextBox,
            this.toolStripSeparator5,
            this.GCCTtoolStripMenuItem});
            this.OtherToolStripMenuItem.Name = "OtherToolStripMenuItem";
            this.OtherToolStripMenuItem.Size = new System.Drawing.Size(204, 24);
            this.OtherToolStripMenuItem.Text = "Other";
            // 
            // lowMemoryMappedIoSpaceToolStripMenuItem
            // 
            this.lowMemoryMappedIoSpaceToolStripMenuItem.Enabled = false;
            this.lowMemoryMappedIoSpaceToolStripMenuItem.Name = "lowMemoryMappedIoSpaceToolStripMenuItem";
            this.lowMemoryMappedIoSpaceToolStripMenuItem.Size = new System.Drawing.Size(320, 26);
            this.lowMemoryMappedIoSpaceToolStripMenuItem.Text = "LowMemoryMappedIoSpace(MB)";
            // 
            // LMMIOtoolStripTextBox
            // 
            this.LMMIOtoolStripTextBox.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.LMMIOtoolStripTextBox.MaxLength = 4;
            this.LMMIOtoolStripTextBox.Name = "LMMIOtoolStripTextBox";
            this.LMMIOtoolStripTextBox.Size = new System.Drawing.Size(100, 27);
            this.LMMIOtoolStripTextBox.KeyDown += new System.Windows.Forms.KeyEventHandler(this.LMMIOtoolStripTextBox_KeyDown);
            // 
            // toolStripSeparator4
            // 
            this.toolStripSeparator4.Name = "toolStripSeparator4";
            this.toolStripSeparator4.Size = new System.Drawing.Size(317, 6);
            // 
            // highMemoryMappedIoSpaceToolStripMenuItem
            // 
            this.highMemoryMappedIoSpaceToolStripMenuItem.Enabled = false;
            this.highMemoryMappedIoSpaceToolStripMenuItem.Name = "highMemoryMappedIoSpaceToolStripMenuItem";
            this.highMemoryMappedIoSpaceToolStripMenuItem.Size = new System.Drawing.Size(320, 26);
            this.highMemoryMappedIoSpaceToolStripMenuItem.Text = "HighMemoryMappedIoSpace(MB)";
            // 
            // HMMIOtoolStripTextBox
            // 
            this.HMMIOtoolStripTextBox.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.HMMIOtoolStripTextBox.MaxLength = 5;
            this.HMMIOtoolStripTextBox.Name = "HMMIOtoolStripTextBox";
            this.HMMIOtoolStripTextBox.Size = new System.Drawing.Size(100, 27);
            this.HMMIOtoolStripTextBox.KeyDown += new System.Windows.Forms.KeyEventHandler(this.HMMIOtoolStripTextBox_KeyDown);
            // 
            // toolStripSeparator5
            // 
            this.toolStripSeparator5.Name = "toolStripSeparator5";
            this.toolStripSeparator5.Size = new System.Drawing.Size(317, 6);
            // 
            // GCCTtoolStripMenuItem
            // 
            this.GCCTtoolStripMenuItem.Checked = true;
            this.GCCTtoolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked;
            this.GCCTtoolStripMenuItem.Name = "GCCTtoolStripMenuItem";
            this.GCCTtoolStripMenuItem.Size = new System.Drawing.Size(320, 26);
            this.GCCTtoolStripMenuItem.Text = "GuestControlledCacheTypes";
            this.GCCTtoolStripMenuItem.Click += new System.EventHandler(this.GCCTtoolStripMenuItem_Click);
            // 
            // toolStripSeparator2
            // 
            this.toolStripSeparator2.Name = "toolStripSeparator2";
            this.toolStripSeparator2.Size = new System.Drawing.Size(201, 6);
            // 
            // AddDeviceToolStripMenuItem
            // 
            this.AddDeviceToolStripMenuItem.Name = "AddDeviceToolStripMenuItem";
            this.AddDeviceToolStripMenuItem.Size = new System.Drawing.Size(204, 24);
            this.AddDeviceToolStripMenuItem.Text = "Add a device";
            this.AddDeviceToolStripMenuItem.Click += new System.EventHandler(this.AddDeviceToolStripMenuItem_Click);
            // 
            // RemoveDeviceToolStripMenuItem
            // 
            this.RemoveDeviceToolStripMenuItem.Name = "RemoveDeviceToolStripMenuItem";
            this.RemoveDeviceToolStripMenuItem.Size = new System.Drawing.Size(204, 24);
            this.RemoveDeviceToolStripMenuItem.Text = "Remove the device";
            this.RemoveDeviceToolStripMenuItem.Click += new System.EventHandler(this.RemoveDeviceToolStripMenuItem_Click);
            // 
            // CopyAddressToolStripMenuItem
            // 
            this.CopyAddressToolStripMenuItem.Name = "CopyAddressToolStripMenuItem";
            this.CopyAddressToolStripMenuItem.Size = new System.Drawing.Size(204, 24);
            this.CopyAddressToolStripMenuItem.Text = "Copy the address";
            this.CopyAddressToolStripMenuItem.Click += new System.EventHandler(this.CopyAddressToolStripMenuItem_Click);
            // 
            // toolStripSeparator1
            // 
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new System.Drawing.Size(201, 6);
            // 
            // RefreshToolStripMenuItem
            // 
            this.RefreshToolStripMenuItem.Name = "RefreshToolStripMenuItem";
            this.RefreshToolStripMenuItem.Size = new System.Drawing.Size(204, 24);
            this.RefreshToolStripMenuItem.Text = "Refresh the list";
            this.RefreshToolStripMenuItem.Click += new System.EventHandler(this.RefreshToolStripMenuItem_Click);
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(839, 575);
            this.Controls.Add(this.listView1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.Name = "MainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Discrete Device Assigner";
            this.Load += new System.EventHandler(this.Form1_Load);
            this.contextMenuStrip.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.ListView listView1;
        private System.Windows.Forms.ColumnHeader columnHeaderDevice;
        private System.Windows.Forms.ColumnHeader columnHeaderLocation;
        private System.Windows.Forms.ColumnHeader columnHeaderClass;
        private System.Windows.Forms.ContextMenuStrip contextMenuStrip;
        private System.Windows.Forms.ToolStripMenuItem vMNameToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem AddDeviceToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem RemoveDeviceToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
        private System.Windows.Forms.ToolStripMenuItem RefreshToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator2;
        private System.Windows.Forms.ToolStripMenuItem CopyAddressToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem OtherToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem lowMemoryMappedIoSpaceToolStripMenuItem;
        private System.Windows.Forms.ToolStripTextBox LMMIOtoolStripTextBox;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator4;
        private System.Windows.Forms.ToolStripMenuItem highMemoryMappedIoSpaceToolStripMenuItem;
        private System.Windows.Forms.ToolStripTextBox HMMIOtoolStripTextBox;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator5;
        private System.Windows.Forms.ToolStripMenuItem GCCTtoolStripMenuItem;
    }
}

